### ISSUE TITLE
binary: use -h for help

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-grape#15]
usually `-h` is reserved for calling the help of a CLI.

Maybe we can set the host to `-b` as with `--bind`?

What do you think?

**Comment by prdn** [comment]
@robertkowalski that sounds good to me

**Comment by prdn** [comment]
ps. please adjust the documentation in all projects (and blog post) accordingly where needed

**Comment by robertkowalski** [comment]
all fixed i think
