### ISSUE TITLE
avoid ddossing with announce 

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-grape#49]
via @mafintosh 

Currently when we start a lot of clients/workers, lets say 50, they will all announce at the same time. The idea is to put some randomness / delay into the link.announce function.

example:

```
ann => link.announce(..., () => setTimeout(ann, 2min + random() * 1min))
```

**Comment by prdn** [comment]
Good idea, we should place it in the `grenache-link` I think. Grape should be really simple and predictable

**Comment by mafintosh** [comment]
@prdn a `link.keepAnnouncing(name)` api perhaps, in addition to the simple one we have already (open for better names)

**Comment by prdn** [comment]
@mafintosh yep, I like it! `startAnnouncing` ?
we should have a `stopAnnouncing` as well probably

**Comment by quadramadery** [comment]
looks like you did this one already:
https://github.com/bitfinexcom/grenache-nodejs-link/commit/861c1b3caaa0e42aa45d72d723fd0babc80f3e99

close?

**Comment by robertkowalski** [comment]
@quadramadery good point, closing now. thx!
