### ISSUE TITLE
Creating a grape without dht_bootstrap set should be supported

### ISSUE THREAD

**Issue by allain** [bitfinexcom/grenache-grape#6]
var grape = new Grape({dht_port: 20000, api_port: 20001})

``` js
grape.announce('test', 1000, () => {
  // at this point another instance could be started and lookup test
})
```

One workaround that seems to work is to bootstrap the dht with itself.

**Comment by prdn** [comment]
Reading here it seems like a good idea, especially in testing phase or simple environments: https://github.com/feross/bittorrent-dht/issues/59
Yeah, it should work
